### PR TITLE
Apply full-capture in Mac for consistency

### PR DESCRIPTION
**Pull request by fritx**
Hey @uiureo. I'm not sure about this.
How do you think of it?

### CODE REVIEW

**Comment by uiur** [comment]
Hi @fritx. The interactive behavior is correct. 
`import screenshot.png` runs interactively.

> Running import without the -window option allows selecting a window or an arbitrary region interactively.
> https://wiki.archlinux.org/index.php/Taking_a_screenshot

I've realized its description is not clear. Sorry for that.

If you want to take a full-screen screenshot, it might be good to have an option like `{ fullscreen: true }`.

**Comment by fritx** [comment]
Yes it's great! I'm expecting something like `{ fullscreen: true }`
~~It seems in win32 nircmd supports region selection, too~~ http://nircmd.nirsoft.net/savescreenshot.html

**Comment by fritx** [comment]
update: It seems in win32 nircmd doesn't support region selection. What should we do?

**Comment by uiur** [comment]
> It seems in win32 nircmd doesn't support region selection.

We should use other module that allows users to select region interactively. 
I've just found a module, but I'm not sure it works because I don't even have a Windows.
https://github.com/mdrasmus/boxcutter

**Comment by fritx** [comment]
It is great! I've tested it in my Windows (win7 x64).
Both of `boxcutter.exe` & `boxcutter-fs.exe` work.
And without a filename specified, they paste the picture to clipboard.
However there are a few little problems:
- `boxcutter.exe` won't exit even though it saves file successfully (kind of like nircmdc problem).
- As documented, the `-fs.exe` is faster and recommended for fullscreen, but I found it doesn't work for clipboard without filename input, while `boxcutter.exe -f` is okay.

**Pull request closed without merging**
